'use client';

import * as React from 'react';
import Link from 'next/link';
import { FileText, Shield, CheckCircle2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Footer } from '@/components/layout/footer';

export default function TermsPage() {
  return (
    <div className="flex-1 flex flex-col bg-[#070711]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-10">
        <div className="space-y-3">
          <Badge variant="primary">Terms of Service</Badge>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white">
            Platform Terms & Conditions
          </h1>
          <p className="text-xs text-muted-foreground">
            Effective Date: August 31, 2026 • InterviewAI SaaS Terms
          </p>
        </div>

        <div className="space-y-6 text-xs sm:text-sm text-foreground/90 leading-relaxed">
          <div className="rounded-2xl bg-surface border border-white/10 p-6 space-y-2 shadow-xl">
            <h3 className="text-base font-bold text-white">1. Practice & Educational Purpose</h3>
            <p className="text-muted-foreground">
              InterviewAI is an educational AI mock interview coaching platform designed to simulate typical technical and behavioral job interviews. Interview questions, difficulty calibrations, and scoring feedback are generated by artificial intelligence models for skill improvement and do not guarantee hiring outcomes with any third-party employer.
            </p>
          </div>

          <div className="rounded-2xl bg-surface border border-white/10 p-6 space-y-2 shadow-xl">
            <h3 className="text-base font-bold text-white">2. Acceptable Use</h3>
            <p className="text-muted-foreground">
              Users agree to utilize the platform for lawful professional preparation. Reverse engineering AI prompt mechanisms, scraping questions at scale, or injecting malicious payloads into resume upload endpoints is strictly prohibited.
            </p>
          </div>

          <div className="rounded-2xl bg-surface border border-white/10 p-6 space-y-2 shadow-xl">
            <h3 className="text-base font-bold text-white">3. Intellectual Property</h3>
            <p className="text-muted-foreground">
              Company trademarks, logos, and brand names referenced in role presets (such as Google, Amazon, Microsoft, etc.) belong to their respective owners. Their inclusion is purely illustrative of industry technical archetypes and does not imply official endorsement or affiliation.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
