import { RolePreset, InterviewSession } from '@/types/interview';
import { UserProfile, UserStats } from '@/types/user';

export const ROLE_PRESETS: RolePreset[] = [
  {
    id: 'full-stack-developer',
    title: 'Full Stack Developer',
    category: 'Engineering',
    iconName: 'Layers',
    description: 'Master front-to-back architectures, React, Next.js, Node.js, databases, REST/GraphQL APIs, and deployment pipelines.',
    keySkills: ['React', 'Next.js', 'Node.js', 'PostgreSQL', 'REST APIs', 'System Design'],
    popularCompanies: ['Google', 'Amazon', 'Microsoft', 'Zoho', 'Flipkart'],
  },
  {
    id: 'frontend-developer',
    title: 'Frontend Developer',
    category: 'Engineering',
    iconName: 'Layout',
    description: 'Master modern UI engineering, React lifecycle, State Management, CSS/Tailwind, performance optimization, and Web APIs.',
    keySkills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'Web Vitals', 'Accessibility'],
    popularCompanies: ['Microsoft', 'Amazon', 'Flipkart', 'Zoho'],
  },
  {
    id: 'backend-developer',
    title: 'Backend Developer',
    category: 'Engineering',
    iconName: 'Server',
    description: 'Deep dive into distributed systems, microservices, concurrency, caching, relational/NoSQL databases, and security.',
    keySkills: ['Node.js', 'Python', 'Go', 'PostgreSQL', 'Redis', 'Kafka', 'Docker'],
    popularCompanies: ['Amazon', 'Google', 'Uber', 'TCS', 'Infosys'],
  },
  {
    id: 'software-engineer',
    title: 'Software Engineer',
    category: 'Engineering',
    iconName: 'Code',
    description: 'Core computer science fundamentals, data structures, algorithms, object-oriented design patterns, and debugging.',
    keySkills: ['DSA', 'OOP', 'System Architecture', 'C++', 'Java', 'Python'],
    popularCompanies: ['Google', 'Microsoft', 'Amazon', 'TCS', 'Accenture'],
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    category: 'Data & AI',
    iconName: 'Brain',
    description: 'Statistical modeling, machine learning pipelines, predictive analytics, feature engineering, and hypothesis testing.',
    keySkills: ['Python', 'Pandas', 'Scikit-Learn', 'TensorFlow', 'SQL', 'Statistics'],
    popularCompanies: ['Google', 'Amazon', 'Flipkart', 'Microsoft'],
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    category: 'Data & AI',
    iconName: 'BarChart3',
    description: 'Extract business insights with advanced SQL, Tableau/PowerBI dashboards, exploratory data analysis, and metrics definition.',
    keySkills: ['SQL', 'Python', 'PowerBI', 'Tableau', 'Excel', 'Business Intelligence'],
    popularCompanies: ['Accenture', 'Infosys', 'TCS', 'Flipkart'],
  },
  {
    id: 'aiml-engineer',
    title: 'AI/ML Engineer',
    category: 'Data & AI',
    iconName: 'Sparkles',
    description: 'Deep learning, neural network architectures, LLMs, fine-tuning, RAG pipelines, and model deployment/serving at scale.',
    keySkills: ['PyTorch', 'Transformers', 'LangChain', 'RAG', 'Vector DBs', 'MLOps'],
    popularCompanies: ['OpenAI', 'Google DeepMind', 'Microsoft', 'Amazon'],
  },
  {
    id: 'devops-engineer',
    title: 'DevOps Engineer',
    category: 'Security & Ops',
    iconName: 'GitBranch',
    description: 'CI/CD automation, Kubernetes orchestration, Infrastructure as Code (Terraform), observability, and cloud scalability.',
    keySkills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'GitHub Actions', 'Prometheus'],
    popularCompanies: ['Amazon', 'Google', 'Accenture', 'Microsoft'],
  },
  {
    id: 'cloud-engineer',
    title: 'Cloud Engineer',
    category: 'Security & Ops',
    iconName: 'Cloud',
    description: 'Cloud architecture design across AWS, Azure, GCP, VPC networking, IAM security, serverless compute, and cost governance.',
    keySkills: ['AWS', 'Azure', 'GCP', 'Networking', 'Serverless', 'Security'],
    popularCompanies: ['Amazon', 'Microsoft', 'Infosys', 'TCS'],
  },
  {
    id: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'Security & Ops',
    iconName: 'ShieldCheck',
    description: 'Threat hunting, vulnerability assessment, network defense, penetration testing concepts, and incident response.',
    keySkills: ['Network Security', 'OWASP Top 10', 'SIEM', 'Cryptography', 'Compliance'],
    popularCompanies: ['Microsoft', 'Accenture', 'TCS', 'Infosys'],
  },
  {
    id: 'mobile-developer',
    title: 'Mobile Developer',
    category: 'Engineering',
    iconName: 'Smartphone',
    description: 'Native & cross-platform mobile apps using React Native, Flutter, Swift, or Kotlin with offline caching and animations.',
    keySkills: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Mobile Architecture'],
    popularCompanies: ['Flipkart', 'Zoho', 'Uber', 'Google'],
  },
  {
    id: 'ui-ux-designer',
    title: 'UI/UX Designer',
    category: 'Design & Product',
    iconName: 'Palette',
    description: 'User research, wireframing, high-fidelity Figma prototypes, design systems, usability testing, and design-to-code handover.',
    keySkills: ['Figma', 'Design Systems', 'User Research', 'Wireframing', 'Prototyping'],
    popularCompanies: ['Zoho', 'Flipkart', 'Microsoft', 'Google'],
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    category: 'Design & Product',
    iconName: 'Target',
    description: 'Product strategy, roadmap prioritization, user persona definition, KPI tracking, agile execution, and stakeholder alignment.',
    keySkills: ['Product Strategy', 'Roadmapping', 'Agile/Scrum', 'User Metrics', 'A/B Testing'],
    popularCompanies: ['Google', 'Microsoft', 'Amazon', 'Flipkart'],
  },
  {
    id: 'business-analyst',
    title: 'Business Analyst',
    category: 'Design & Product',
    iconName: 'Briefcase',
    description: 'Requirements elicitation, process flow mapping, user story grooming, feasibility studies, and stakeholder management.',
    keySkills: ['Requirements Analysis', 'BPMN', 'Jira', 'SQL', 'Stakeholder Management'],
    popularCompanies: ['Accenture', 'Infosys', 'TCS', 'Zoho'],
  },
  {
    id: 'qa-engineer',
    title: 'QA Engineer',
    category: 'Engineering',
    iconName: 'CheckCircle2',
    description: 'Automated end-to-end testing, unit/integration frameworks, Playwright/Cypress, performance testing, and bug tracking.',
    keySkills: ['Selenium', 'Playwright', 'Jest', 'API Testing', 'Postman', 'Test Automation'],
    popularCompanies: ['Infosys', 'TCS', 'Accenture', 'Amazon'],
  },
  {
    id: 'database-administrator',
    title: 'Database Administrator',
    category: 'Security & Ops',
    iconName: 'Database',
    description: 'Query optimization, indexing strategies, replication, backup & disaster recovery, ACID guarantees, and database tuning.',
    keySkills: ['PostgreSQL', 'MySQL', 'Query Optimization', 'Replication', 'High Availability'],
    popularCompanies: ['Oracle', 'Amazon', 'Microsoft', 'TCS'],
  },
];

export const DEMO_USER: UserProfile = {
  id: 'demo-user-123',
  name: 'Yogesh',
  email: 'yogesh.dev@interviewai.io',
  phone: '+91 98765 43210',
  college: 'National Institute of Technology',
  degree: 'B.Tech in Computer Science & Engineering',
  graduationYear: '2025',
  targetRole: 'Full Stack Developer',
  experienceLevel: 'Fresher',
  preferredInterviewType: 'Technical',
  skills: ['JavaScript', 'TypeScript', 'React.js', 'Next.js', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'REST APIs', 'Git', 'Docker'],
  bio: 'Aspiring Full Stack Engineer passionate about high-performance web applications, distributed systems, and modern AI-driven developer tooling.',
  createdAt: '2026-01-15T10:00:00Z',
};

export const DEMO_STATS: UserStats = {
  interviewsCompleted: 12,
  averageScore: 8.4,
  bestScore: 9.3,
  currentStreak: 5,
  totalTimeMinutes: 145,
  skillBreakdown: {
    technicalKnowledge: 82,
    communication: 76,
    confidence: 84,
    problemSolving: 79,
    relevance: 88,
  },
  scoreHistory: [
    { id: '1', date: 'Aug 12', score: 6.8, role: 'Full Stack Developer' },
    { id: '2', date: 'Aug 15', score: 7.2, role: 'Frontend Developer' },
    { id: '3', date: 'Aug 18', score: 7.5, role: 'Full Stack Developer' },
    { id: '4', date: 'Aug 20', score: 7.9, role: 'Software Engineer' },
    { id: '5', date: 'Aug 22', score: 8.1, role: 'Backend Developer' },
    { id: '6', date: 'Aug 24', score: 8.4, role: 'Full Stack Developer' },
    { id: '7', date: 'Aug 26', score: 8.6, role: 'Frontend Developer' },
    { id: '8', date: 'Aug 28', score: 8.9, role: 'Full Stack Developer' },
    { id: '9', date: 'Aug 29', score: 9.1, role: 'Software Engineer' },
    { id: '10', date: 'Aug 31', score: 9.3, role: 'Full Stack Developer' },
  ],
};

export const DEMO_INTERVIEW_HISTORY: InterviewSession[] = [
  {
    id: 'demo-interview-101',
    userId: 'demo-user-123',
    role: 'Full Stack Developer',
    level: 'Fresher',
    interviewType: 'Technical',
    durationMinutes: 10,
    voiceGender: 'female',
    currentQuestionIndex: 2,
    status: 'completed',
    overallScore: 8.6,
    startedAt: '2026-08-31T09:30:00Z',
    completedAt: '2026-08-31T09:41:00Z',
    questions: [
      {
        id: 'q1',
        interviewId: 'demo-interview-101',
        questionNumber: 1,
        question: 'Can you walk me through the difference between authentication and authorization in a web application?',
        questionType: 'technical',
        difficulty: 'Easy',
        category: 'Web Security',
        userAnswer: 'Authentication verifies who a user is, for example using username and password or OAuth tokens. Authorization determines what resources or actions the authenticated user has permission to access, like admin roles versus regular users.',
        userAudioTranscript: 'Authentication verifies who a user is, for example using username and password or OAuth tokens. Authorization determines what resources or actions the authenticated user has permission to access, like admin roles versus regular users.',
        evaluation: {
          technicalScore: 9.0,
          communicationScore: 8.8,
          relevanceScore: 9.5,
          depthScore: 8.2,
          confidenceScore: 8.5,
          problemSolvingScore: 8.5,
          whatWasGood: [
            'Clear and crisp distinction with real-world examples (OAuth, admin roles)',
            'Concise terminology without unnecessary filler',
          ],
          whatCouldImprove: [
            'Could mention token mechanisms like JWT claims and RBAC (Role Based Access Control)',
          ],
          idealAnswerStructure: '1. Definition of Authentication (Identity verification: "Who you are")\n2. Definition of Authorization (Permission evaluation: "What you can do")\n3. Real-world example (e.g. Passport vs Boarding Pass)\n4. Implementation details (JWT, Session cookies, RBAC/ABAC)',
          keyConceptsMentioned: ['Authentication', 'Authorization', 'OAuth', 'Tokens', 'Roles'],
        },
      },
      {
        id: 'q2',
        interviewId: 'demo-interview-101',
        questionNumber: 2,
        question: 'You mentioned tokens. How do you securely store JSON Web Tokens (JWT) on the client side to prevent XSS and CSRF attacks?',
        questionType: 'followup',
        difficulty: 'Medium',
        category: 'Security & State',
        userAnswer: 'Storing tokens in localStorage makes them vulnerable to XSS attacks if malicious scripts execute. The most secure approach is storing JWT access tokens in memory and refresh tokens in HttpOnly, Secure, SameSite cookies so JavaScript cannot read them directly.',
        userAudioTranscript: 'Storing tokens in localStorage makes them vulnerable to XSS attacks if malicious scripts execute. The most secure approach is storing JWT access tokens in memory and refresh tokens in HttpOnly, Secure, SameSite cookies so JavaScript cannot read them directly.',
        evaluation: {
          technicalScore: 9.2,
          communicationScore: 8.6,
          relevanceScore: 9.2,
          depthScore: 9.0,
          confidenceScore: 8.8,
          problemSolvingScore: 8.9,
          whatWasGood: [
            'Accurately identified vulnerabilities of localStorage against XSS',
            'Highlighted HttpOnly, Secure, and SameSite cookie attributes',
          ],
          whatCouldImprove: [
            'Could briefly mention CSRF tokens as an added defense when using cookies',
          ],
          idealAnswerStructure: '1. Vulnerability of localStorage (XSS risks)\n2. Vulnerability of plain cookies (CSRF risks)\n3. Best Practice: HttpOnly, Secure, SameSite=Strict/Lax cookies + CSRF protection tokens',
          keyConceptsMentioned: ['HttpOnly', 'Secure Cookie', 'SameSite', 'XSS', 'CSRF', 'In-memory token'],
        },
      },
      {
        id: 'q3',
        interviewId: 'demo-interview-101',
        questionNumber: 3,
        question: 'Tell me about a challenging full-stack project you built and how you handled database performance or query optimization.',
        questionType: 'behavioral',
        difficulty: 'Medium',
        category: 'Project Architecture',
        userAnswer: 'In my college e-commerce project, product search queries were taking over 2 seconds under concurrent loads. I profiled the slow queries in PostgreSQL and discovered we were doing full table scans on category and price columns. I added composite B-Tree indexes and integrated Redis caching for hot product listings, which dropped response times below 80ms.',
        userAudioTranscript: 'In my college e-commerce project, product search queries were taking over 2 seconds under concurrent loads. I profiled the slow queries in PostgreSQL and discovered we were doing full table scans on category and price columns. I added composite B-Tree indexes and integrated Redis caching for hot product listings, which dropped response times below 80ms.',
        evaluation: {
          technicalScore: 8.8,
          communicationScore: 8.5,
          relevanceScore: 9.0,
          depthScore: 8.5,
          confidenceScore: 8.7,
          problemSolvingScore: 9.0,
          whatWasGood: [
            'Followed the STAR method naturally with measurable results (2s down to 80ms)',
            'Mentioned concrete optimization tools: PostgreSQL indexing and Redis caching',
          ],
          whatCouldImprove: [
            'Could elaborate on cache invalidation strategy when product inventory updates',
          ],
          idealAnswerStructure: '1. Situation & Problem: Slow search queries affecting user experience\n2. Task: Identify bottlenecks and optimize response times\n3. Action: EXPLAIN ANALYZE, B-Tree indexes, Redis caching layer\n4. Result: Quantitative improvement from 2000ms to 80ms',
          keyConceptsMentioned: ['PostgreSQL', 'Indexes', 'Redis', 'Full table scan', 'Query latency'],
          starAnalysis: {
            situation: { present: true, feedback: 'Clearly described the slow e-commerce query bottleneck under load' },
            task: { present: true, feedback: 'Defined the objective of reducing search latency' },
            action: { present: true, feedback: 'Implemented indexing and Redis caching after query profiling' },
            result: { present: true, feedback: 'Demonstrated measurable 2s -> 80ms improvement' },
            overallStarScore: 8.8,
            advice: 'Great STAR structure! Next time add a brief mention of cache invalidation or concurrency trade-offs.',
          },
        },
      },
    ],
    report: {
      id: 'report-101',
      interviewId: 'demo-interview-101',
      overallScore: 8.6,
      technicalScore: 8.8,
      communicationScore: 8.4,
      confidenceScore: 8.6,
      problemSolvingScore: 8.7,
      relevanceScore: 9.1,
      strengths: [
        'Demonstrated strong grasp of web security concepts (Authentication vs Authorization, JWT storage)',
        'Effectively structured project experiences using the STAR method with quantitative metrics',
        'Clear articulation of architectural trade-offs between relational databases and Redis caching',
      ],
      weaknesses: [
        'Could go deeper into cache invalidation strategies (e.g. write-through vs cache-aside)',
        'Can add explicit mentions of Role-Based Access Control (RBAC) implementation nuances',
      ],
      recommendations: [
        'REST API Design & Idempotency Keys',
        'PostgreSQL Indexing & EXPLAIN ANALYZE Deep Dive',
        'JWT Refresh Rotation & OAuth 2.0 PKCE Flow',
        'Distributed Caching & Invalidation Patterns',
      ],
      summary: 'Outstanding performance for a fresher candidate. Showed thorough technical clarity, solid architectural intuition, and disciplined problem-solving methodology.',
      createdAt: '2026-08-31T09:41:00Z',
    },
  },
  {
    id: 'demo-interview-102',
    userId: 'demo-user-123',
    role: 'Frontend Developer',
    level: 'Fresher',
    interviewType: 'Technical',
    durationMinutes: 10,
    voiceGender: 'male',
    currentQuestionIndex: 0,
    status: 'completed',
    overallScore: 8.2,
    startedAt: '2026-08-28T14:15:00Z',
    completedAt: '2026-08-28T14:26:00Z',
    questions: [],
    report: {
      id: 'report-102',
      interviewId: 'demo-interview-102',
      overallScore: 8.2,
      technicalScore: 8.4,
      communicationScore: 8.0,
      confidenceScore: 8.1,
      problemSolvingScore: 8.3,
      relevanceScore: 8.5,
      strengths: ['Great command of React Hooks lifecycle and virtual DOM reconciliation.'],
      weaknesses: ['Spend more time on Core Web Vitals (LCP, FID, CLS).'],
      recommendations: ['React Server Components', 'Bundle Splitting & Lazy Loading', 'CSS Grid & Flexbox layouts'],
      summary: 'Solid frontend fundamentals with high accuracy in React ecosystem principles.',
      createdAt: '2026-08-28T14:26:00Z',
    }
  },
  {
    id: 'demo-interview-103',
    userId: 'demo-user-123',
    role: 'Software Engineer',
    level: 'Fresher',
    interviewType: 'Mixed',
    durationMinutes: 15,
    voiceGender: 'female',
    currentQuestionIndex: 0,
    status: 'completed',
    overallScore: 7.9,
    startedAt: '2026-08-24T18:00:00Z',
    completedAt: '2026-08-24T18:16:00Z',
    questions: [],
    report: {
      id: 'report-103',
      interviewId: 'demo-interview-103',
      overallScore: 7.9,
      technicalScore: 8.0,
      communicationScore: 7.8,
      confidenceScore: 7.9,
      problemSolvingScore: 8.1,
      relevanceScore: 8.2,
      strengths: ['Good grasp of OOP concepts and basic Data Structures.'],
      weaknesses: ['Practice explaining time-space complexity tradeoffs more fluently.'],
      recommendations: ['Binary Trees & Graphs', 'Dynamic Programming Patterns', 'SOLID Principles'],
      summary: 'Demonstrated solid fundamentals with clear potential in algorithms and systems thinking.',
      createdAt: '2026-08-24T18:16:00Z',
    }
  },
];
